=== wsilveiranz/LA-UnitTest-Demo-Integrate/LogicApps/Artifacts/Schemas/canonical_order.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "orderId": {
      "type": "string",
      "minLength": 1
    },
    "customerId": {
      "type": "string",
      "minLength": 1
    },
    "region": {
      "type": "string",
      "minLength": 1
    },
    "status": {
      "type": "string",
      "minLength": 1
    },
    "orderDetails": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "productId",
          "productName",
          "quantity",
          "unitPrice"
        ],
        "properties": {
          "productId": {
            "type": "string",
            "minLength": 1
          },
          "productName": {
            "type": "string",
            "minLength": 1
          },
          "quantity": {
            "type": "number"
          },
          "unitPrice": {
            "type": "number"
          }
        }
      }
    }
  },
  "required": [
    "orderId",
    "customerId",
    "region",
    "status",
    "orderDetails"
  ]
}

=== wsilveiranz/LA-UnitTest-Demo-Integrate/Tests/LogicApps/map-source_order_to_canonical_order/input-01.json
{
  "orderId": "20250603-001",
  "customerId": "X-789456",
  "region": "NA",
  "status": "New",
  "orderDetails": [
    {
      "productId": "BRZ-1001",
      "productName": "Brazilian Coffee Beans - 1kg",
      "quantity": 2,
      "unitPrice": 15
    },
    {
      "productId": "COL-1002",
      "productName": "Colombian Coffee Beans - 1kg",
      "quantity": 1,
      "unitPrice": 10
    },
    {
      "productId": "JAV-1003",
      "productName": "Indonesian Java Coffee Beans - 1kg",
      "quantity": 3,
      "unitPrice": 20
    }
  ]
}
